// users
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const TICKETS_LOADING = "TICKETS_LOADING";
export const TICKETS_LOADED_SUCCESS = "TICKETS_LOADED_SUCCESS";
export const TICKETS_LOADED_FAILURE = "TICKETS_LOADED_FAILURE";

export const ORDERS_LOADING = "ORDERS_LOADING";
export const ORDERS_LOADED_SUCCESS = "ORDERS_LOADED_SUCCESS";
export const ORDERS_LOADED_FAILURE = "ORDERS_LOADED_FAILURE";

export const ORDER_CREATED_SUCCESS = "ORDER_CREATED_SUCCESS";
export const ORDER_CREATED_FAILURE = "ORDER_CREATED_FAILURE";
